<a href="https://colab.research.google.com/github/ckmeher/Daily-Coding-Practice/blob/main/PythonPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

23 may


In [ ]:
p = int(input("Enter initial principal amount: "))
r = float(input("Enter rate of annual interest in percentage: "))
t = int(input("Enter number of years: "))
amount = (p * pow((1 + r/100),t))
CI = amount - p
print('The net amount is {}' .format(amount))
print('The compounf interest is {}' .format(CI))

Enter initial principal amount: 1200
Enter rate of annual interest in percentage: 5.4
Enter number of years: 2
The net amount is 1333.0992
The compounf interest is 133.0992000000001


In [ ]:
radius = float(input("Enter the radius of the circle: "))
area = 3.14 * radius * radius
print('Area of the circle is {}' .format(area))

Enter the radius of the circle: 2
Area of the circle is 12.56


In [ ]:
num = int(input('Enter a postive integer greater than one: '))
a = 0
for i in range(2,num):
    if num % i == 0:
      a = a+1
if a > 0:
  print('The number is not prime number')
else:
  print ('The number is a prime number')


Enter a postive integer greater than one: 102
The number is not prime number


In [ ]:
start = int(input('Enter the starting integer of the interval: '))
end = int(input('Enter the end integer of the interval: '))
for i in range(start,end+1):
  a = 0
  for j in range(2,i):
    if i % j == 0:
      a = a + 1
  if a == 0:
    print("{} is a prime number" .format(i))
#print('There are {} prime numbers between the interval' .format(b) )

Enter the starting integer of the interval: 2
Enter the end integer of the interval: 8
2 is a prime number
3 is a prime number
5 is a prime number
7 is a prime number


In the above program, use break to optimize the code

25 may

In [ ]:
num = int(input('Enter the number to calculate the sum of square of first n natural number: '))
n1 = (num * (num +1) * ((2*num) +1)/6)
print('The sum of the sqaure of first {} natural number is {} ' .format(num,n1))

Enter the number to calculate the sum of square of first n natural number: 100
The sum of the sqaure of first 100 natural number is 338350.0 


In [ ]:
num = int(input('Enter the number to calculate the sum of cube of first n natural number: '))
n1 = pow((num * (num +1) / 2),2)
print('The sum of the cube of first {} natural number is {} ' .format(num,n1))

Enter the number to calculate the sum of cube of first n natural number: 25
The sum of the cube of first 25 natural number is 105625.0 


In [ ]:
n = int(input('Enter the number to get nth fibonacci number: '))
a1 = 1
a2 = 1
a3 = 0
for i in range(1,n-1):
  a3 = a1 + a2
  a1 = a2
  a2 = a3
print('The {} th fibonacci number is {} ' .format(n,a3))

Enter the number to get nth fibonacci number: 12
The 12 th fibonacci number is 144 


In [ ]:
import math
n = int(input('Enter the number: '))
n1 = (5*n*n)+4
n2 = (5*n*n)-4


Enter the number: 5


In [ ]:
import math
n = 100
sqrt = math.sqrt(n)
print(sqrt)

10.0


27 may


In [ ]:
n = int(input('Enter the 3 digit number to check it is amstrong number or not: '))
n1 = n // 100
n2 = n - 100*(n1)
n3 = n2 // 10
n4 = n2 - 10*(n3)
n5 = (pow(n1,3) + pow(n3,3) + pow(n4,3))
n6 = n5 - n
#print(n1,n2,n3,n4,n5,n6)
if n6 == 0:
  print('Yes')
else:
  print('No')

Enter the 3 digit number to check it is amstrong number or not: 120
No


In [ ]:
num = int(input('Enter the 4 digit number to check it is amstrong number or not: '))
n5 = num // 1000
n = num - 1000*(n5)
n1 = n // 100
n2 = n - 100*(n1)
n3 = n2 // 10
n4 = n2 - 10*(n3)
n6 = (pow(n5,4) + pow(n1,4) + pow(n3,4) + pow(n4,4))
n7 = n6 - num
print(num, n5, n1, n3, n4, n6, n7)
if n7 == 0:
  print('Yes')
else:
  print('No')

Enter the 4 digit number to check it is amstrong number or not: 1634
1634 1 6 3 4 1634 0
Yes


In [ ]:
import math
n = int(input('Enter a number to check if it is a fibonacci number or not '))
a = ((5*pow(n,2)) + 4)
b = ((5*pow(n,2)) - 4)
c = int(math.sqrt(a))
d = int(math.sqrt(b))
e = a - (c*c)
f = b - (d*d)
print(e, f)
if e == 0 or f == 0:
  print('Yes')
else:
  print('No')


Enter a number to check if it is a fibonacci number or not 41
128 120
No


In [ ]:
c = input('Enter a character: ')
# print the ASCII value of assigned character in c
print("The ASCII value of '" + c + "' is", ord(c))

Enter a character: a
The ASCII value of 'a' is 97


In [ ]:
print('Implementing pow function')
a = int(input('Enter the base: '))
b = int(input('Enter the exponent: '))

d = a
for i in range(1,b):
    d = d * a
print('{} to the power {} is {} '.format(a,b,d))

Implementing pow function
Enter the base: 0
Enter the exponent: 4
0 to the power 4 is 0 


In [ ]:
print('Implementing pow function')
a = int(input('Enter the base: '))
b = int(input('Enter the exponent: '))
print(a, b)
d = a

if b == 0:
  print (1)
elif a == 0:
  print (0)
else:
  for i in range(1,b):
    d = d * a
print(d)

Implementing pow function
Enter the base: 3
Enter the exponent: 2
3 2
9


24 june coding practice

In [ ]:
#Maximum between two integer numbers 

def maximum(a,b):
  if a == b:
    print('Both numbers are equal') 
  elif a > b:
    return a
  else:
    return b

#Driver class
print(maximum(5,4))

print(max(10,4)) #using direct function

5
10


In [ ]:
#To find the factorial of a number
#Recursive approach

def factorial(n):
  if (n == 1 or n == 0):
    return 1
  else:
    return n * factorial(n-1)

#Driver Code
print('Factorial of a number')
print(factorial(10)) 

Factorial of a number
3628800


In [ ]:
#To find the factorial of a number
#Iterative approach

def fact(n):
  if n < 0:
    print('Factorial of negative number is not defined')
  elif n == 0 or n == 1:
    return 1
  else:
    num = 1
    while (n > 1):
      num = num * n
      num = num - 1
    return num

#Driver Code
print('Factorial of a number')
print(factorial(3)) 

Factorial of a number
6


In [ ]:
#To find the factorial of a number
#Using math module

import math

def factori(n):
  return (math.factorial(n))

#Driver Code
print('Factorial of a number')
print(factori(3)) 

Factorial of a number
6


In [ ]:
#To calculate compund interest

def cinterest(p,r,t):
  amount = (p * pow((1 + r/100),t))
  CI = amount - p
  return CI

#Driver Code
p = int(input("Enter initial principal amount: "))
r = float(input("Enter rate of annual interest in percentage: "))
t = int(input("Enter number of years: "))
print('The compounf interest is')
print(cinterest(p,r,t))

Enter initial principal amount: 1200
Enter rate of annual interest in percentage: 5.4
Enter number of years: 2
The compounf interest is
133.0992000000001


In [ ]:
#Calculate the area of a circle

def circlearea(r):
  area = 3.14 * r * r
  return area

#Driver Code
r = float(input("Enter the radius of the circle: "))
print('Area of the circle is ')
print(circlearea(r))

Enter the radius of the circle: 7
Area of the circle is 
153.86


In [ ]:
#To check the number is prime or not

def prime(n):
  a = 0
  for i in range(2,n):
    if n % i == 0:
      a = a + 1
  if a > 0:
      print('The number is not prime number')
  else:
      print ('The number is a prime number')

#Driver Code
n = int(input('Enter a postive integer greater than one: '))
prime(n)

Enter a postive integer greater than one: 6
The number is not prime number


In [ ]:
#To print all the prime number in an Interval

def primeininterval(start,end):
  for i in range(start,end+1):
    a = 0
    for j in range(2,i):
      if i % j == 0:
        a = a + 1
    if a == 0:
      print("{} is a prime number" .format(i))

#Driver Code
start = int(input('Enter the starting integer of the interval: '))
end = int(input('Enter the end integer of the interval: '))
print('\nThe prime number between the interval are')
primeininterval(start,end)

26 june coding


In [ ]:
#To print all the prime number in an Interval

def PrimeInInterval(start,end):
  for i in range(start,end+1):
      for j in range(2,i):
        if i % j == 0:
          break
      else:
        print (i)

#Driver Code
start = int(input('Enter the starting integer of the interval: '))
end = int(input('Enter the end integer of the interval: '))
print('\nThe prime number between the interval are')
PrimeInInterval(start,end)

Enter the starting integer of the interval: 2
Enter the end integer of the interval: 5

The prime number between the interval are
2
3
5


In [ ]:
#To get the sum of the square of first n natural number

def sumofsquare(num):
  n1 = (num * (num +1) * ((2*num) +1)/6)
  print(n1)

#Driver Code
num = int(input('Enter the number to calculate the sum of square of first n natural number: '))
print('The sum of the sqaure is ')
sumofsquare(num)

Enter the number to calculate the sum of square of first n natural number: 100
The sum of the sqaure of first {} natural number is 
338350.0


In [ ]:
#To get the sum of the cube of first n natural number

def sumofcube(num):
  n1 = pow((num * (num +1) / 2),2)
  print(n1)

#Driver Code
num = int(input('Enter the number to calculate the sum of cube of first n natural number: '))
print('The sum of the cube is')
sumofcube(num)

Enter the number to calculate the sum of cube of first n natural number: 10
The sum of the cube is
3025.0


In [ ]:
#To find the nth fibonacci number

def nfibonacci(n):
  a1 = 1
  a2 = 1
  a3 = 0
  for i in range(1,n-1):
    a3 = a1 + a2
    a1 = a2
    a2 = a3
  print(a3)
  
#Driver code
n = int(input('Enter the number to get nth fibonacci number: '))
print('The nth fibonacci number is ')
nfibonacci(n)

Enter the number to get nth fibonacci number: 12
The nth fibonacci number is 
144


In [ ]:
#To check a number is fibonacci number or not

def fibonaccinum(n):
  import math
  
  a = ((5*pow(n,2)) + 4)
  b = ((5*pow(n,2)) - 4)
  c = int(math.sqrt(a))
  d = int(math.sqrt(b))
  e = a - (c*c)
  f = b - (d*d)
  if e == 0 or f == 0:
    print('Yes')
  else:
    print('No')
  
#Driver code
n = int(input('Enter a number to check if it is a fibonacci number or not: '))
fibonaccinum(n)

Enter a number to check if it is a fibonacci number or not: 41
No


In [ ]:
#To implement the power function

def power(b,e):
  d = 1
  if b == 0:
    return 0
  elif e == 0:
    return 1
  elif b ==1:
    return 1
  else:
    for i in range(1,e+1):
      d = d * b
  print(d)

#Driver Code
b = int(input('Enter the base: '))
e = int(input('Enter the exponent: '))
power(b,e)

Enter the base: 2
Enter the exponent: 10
1024


#29 May

In [ ]:
def power(b,e):
  
  ''' To get the power of a number'''
  d = 1
  if b == 0:
    return 0
  elif e == 0:
    return 1
  elif b ==1:
    return 1
  else:
    for i in range(1,e+1):
      d = d * b
  print(d)

#Driver Code
print(power.__doc__ )
b = int(input('Enter the base: '))
e = int(input('Enter the exponent: '))
power(b,e)

 To get the power of a number
Enter the base: 0
Enter the exponent: 100


0

In [ ]:
def fibonaccinum(n):
  
  ''' To check a number is fibonacci number or not'''
  
  import math
  a = ((5*pow(n,2)) + 4)
  b = ((5*pow(n,2)) - 4)
  c = int(math.sqrt(a))
  d = int(math.sqrt(b))
  e = a - (c*c)
  f = b - (d*d)
  if e == 0 or f == 0:
    print('Yes')
  else:
    print('No')
  
#Driver code
print(fibonaccinum.__doc__)
n = int(input('Enter a number to check if it is a fibonacci number or not: '))
fibonaccinum(n)

 To check a number is fibonacci number or not
Enter a number to check if it is a fibonacci number or not: 44
No


In [ ]:
def nfibonacci(n):

  '''To get the nth fibonacci number'''

  a1 = 1
  a2 = 1
  a3 = 0
  for i in range(1,n-1):
    a3 = a1 + a2
    a1 = a2 
    a2 = a3
  print(a3)
  
#Driver code
print(nfibonacci.__doc__)
n = int(input('Enter the number to get nth fibonacci number: '))
print('The nth fibonacci number is ')
nfibonacci(n)

To get the nth fibonacci number
Enter the number to get nth fibonacci number: 12
The nth fibonacci number is 
144


#1 july

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
sum = 0
for i in a:
  sum = sum + i
print(sum)


[1 2 3 4 5]
15


In [ ]:
import numpy as np

def sumarray(a):
  '''To find the sum of an array '''
  sum = 0
  for i in a:
    print(i)
    sum = sum + i
  print(sum)


#Driver Code
print(sumarray.__doc__)
a = np.array([1,2,3,4,5])
sumarray(a)

To find the sum of an array 
1
2
3
4
5
15


##25 august practise session


In [ ]:
import numpy as np

def largestnum(a):
    '''To find the largest number in the array'''
    
    large = 0
    for i in a:
        #print(i)
        if (i > large):
            large = i
    print('The largest number is {}: ' .format(large))

#Driver Code
print(largestnum.__doc__)
a = np.array([6,2,10,4,5])
largestnum(a)

To find the largest number in the array
The largest number is 10: 


In [ ]:
import numpy as np

def largestnum(a):
    '''To find the largest number in the array'''
    large = 0
    for i in range(0,len(a)):
        #print(a[i])
        if (a[i] > large):
            large = a[i]
    print('The largest number is {}: ' .format(large))

#Driver Code
print(largestnum.__doc__)
a = np.array([1,2,10,4,5])
largestnum(a)

To find the largest number in the array
The largest number is 10: 


In [ ]:
def swaplist(a):
    '''Interchange the first and last element in a list'''
    temp = 0
    temp = a[0]
    a[0] = a[len(a)-1]
    a[len(a)-1] = temp
    print(a)

#Driver Code
print(swaplist.__doc__)
a = np.array([1,2,10,4,5])
swaplist(a)


Interchange the first and last element in a list
[ 5  2 10  4  1]


In [ ]:
def swaplist(a):
    '''Interchange the first and last element in a list'''

    a[0] , a[-1] = a[-1] , a[0]
    print(a)

#Driver Code
print(swaplist.__doc__)
a = np.array([1,2,10,4,5])
swaplist(a)

Interchange the first and last element in a list
[ 5  2 10  4  1]


In [ ]:
def swapposition(a,pos1,pos2):
    '''Swap two elements in a list'''

    a[pos1] , a[pos2] = a[pos2] , a[pos1]
    return a

#Driver Code
print(swapposition.__doc__)
a = np.array([1,2,10,4,5])
pos1 = 1
pos2 = 3
swapposition(a,pos1,pos2)

Swap two elements in a list


array([ 1,  4, 10,  2,  5])

In [ ]:
def listlength(arr):
    '''Find the length of the list'''
    len = 0
    for i in arr:
        len = len + 1
    return len

#Driver Code
print(listlength.__doc__)
arr = np.array([1,2,10,4,5,4,5,6,45,6,56,67,654])
listlength(arr)

Find the length of the list


13